site_name: immerse in trees - Khu học mở
site_description: Guide to self-learning Vietnamese through Comprehensible Input and Immersion.
site_author: khuhocmo  
site_url: https://daihocmo.github.io/learn-vietnamese/
repo_name: Contribute to the site
repo_url: https://github.com/daihocmo/learn-vietnamese

nav:
  - 'Home': 'index.md'
  - 'Guides':
    - 'Vietnamese Guide': 'guide.md'
    - '30 Day Vietnamese': 'routine.md'
    - 'Speaking Vietnamese': 'speaking.md'
    - 'Reading Vietnamese': 'reading.md'
    - 'Reading Techniques and Strategies': 'readingtips.md'
    - 'Monolingual Guide': 'monolingual.md'
    - 'Vietnamese FAQ': 'faq.md' 
  - 'Setup':
    - 'Yomitan': 'yomitan.md'
    - 'Mining': 'mining.md'
  - 'Resources':
    - 'Resources': 'resources.md'


theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/logo.svg
  favicon: assets/fav.svg
  custom_dir: overrides
  features:
    - navigation.sections
    - toc.follow
    - search.highlighting
    - search.share
    - search.suggest
  name: material
  
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
plugins:
  - search
  - open-in-new-tab

extra:
  generator: false